fc = input('Frequency of carrier wave');
fm = input('Frequency of msg signal');
ac = input('amp of carrier wave');
am = input('amp of msg signal');
t = 0:0.001:10;
A = 2*pi*fc*t;
ct = ac*cos(A);
subplot(3,1,1);
plot(t,ct,'r');
xlabel('time');
ylabel('amplitude');
title('carrier signal');
B =2*pi*fm*t;
mt = am*cos(B);
subplot(3,1,2);
plot(t,mt,'g');
xlabel('time');
ylabel('amplitude');
title('message signal');
grid on;
m = fm/fc;
mod = m*mt.*ct
am = ct+mod;
subplot(3,1,3);
plot(t,am,'b');
xlabel('time');
ylabel('amplitude');
title('modulated signal');
grid on;
