t = 0:0.001:1;
vm = input('enter amp (msg)');
vc = input('enter amp (carrier)');
fm = input('enter freq (msg)');
fc = input('enter freq (carrier)');
m = input('modulation index');
msg = vm*sin(2*pi*fm*t);
subplot(3,1,1);
plot(t,msg,'r');
title('message signal');
xlabel('time');
ylabel('amplitude');
grid on;
carrier = vc*sin(2*pi*fc*t);
subplot(3,1,2);
plot(t,carrier,'g');
title('carrier signal');
xlabel('time');
ylabel('amplitude');
grid on;
y = vc*sin(2*pi*fc*t+m.*cos(2*pi*fm*t));
subplot(3,1,3);
plot(t,y,'b');
xlabel('time');
ylabel('amplitude');
title('modualted signal');
grid on;